// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: texture/texture.proto

package texture

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Canvas []byte `protobuf:"bytes,1,opt,name=canvas,proto3" json:"canvas,omitempty"`
}

func (x *TextureRequest) Reset() {
	*x = TextureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_texture_texture_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextureRequest) ProtoMessage() {}

func (x *TextureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_texture_texture_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextureRequest.ProtoReflect.Descriptor instead.
func (*TextureRequest) Descriptor() ([]byte, []int) {
	return file_texture_texture_proto_rawDescGZIP(), []int{0}
}

func (x *TextureRequest) GetCanvas() []byte {
	if x != nil {
		return x.Canvas
	}
	return nil
}

type TextureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Texture []byte `protobuf:"bytes,1,opt,name=texture,proto3" json:"texture,omitempty"`
}

func (x *TextureResponse) Reset() {
	*x = TextureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_texture_texture_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextureResponse) ProtoMessage() {}

func (x *TextureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_texture_texture_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextureResponse.ProtoReflect.Descriptor instead.
func (*TextureResponse) Descriptor() ([]byte, []int) {
	return file_texture_texture_proto_rawDescGZIP(), []int{1}
}

func (x *TextureResponse) GetTexture() []byte {
	if x != nil {
		return x.Texture
	}
	return nil
}

var File_texture_texture_proto protoreflect.FileDescriptor

var file_texture_texture_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x28, 0x0a, 0x0e, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x54, 0x65,
	0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07,
	0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x32, 0x51, 0x0a, 0x0e, 0x54, 0x65, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x47, 0x65, 0x74,
	0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x17, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x2f,
	0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_texture_texture_proto_rawDescOnce sync.Once
	file_texture_texture_proto_rawDescData = file_texture_texture_proto_rawDesc
)

func file_texture_texture_proto_rawDescGZIP() []byte {
	file_texture_texture_proto_rawDescOnce.Do(func() {
		file_texture_texture_proto_rawDescData = protoimpl.X.CompressGZIP(file_texture_texture_proto_rawDescData)
	})
	return file_texture_texture_proto_rawDescData
}

var file_texture_texture_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_texture_texture_proto_goTypes = []interface{}{
	(*TextureRequest)(nil),  // 0: texture.TextureRequest
	(*TextureResponse)(nil), // 1: texture.TextureResponse
}
var file_texture_texture_proto_depIdxs = []int32{
	0, // 0: texture.TextureService.GetTexture:input_type -> texture.TextureRequest
	1, // 1: texture.TextureService.GetTexture:output_type -> texture.TextureResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_texture_texture_proto_init() }
func file_texture_texture_proto_init() {
	if File_texture_texture_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_texture_texture_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_texture_texture_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_texture_texture_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_texture_texture_proto_goTypes,
		DependencyIndexes: file_texture_texture_proto_depIdxs,
		MessageInfos:      file_texture_texture_proto_msgTypes,
	}.Build()
	File_texture_texture_proto = out.File
	file_texture_texture_proto_rawDesc = nil
	file_texture_texture_proto_goTypes = nil
	file_texture_texture_proto_depIdxs = nil
}
