// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: texture/texture.proto

package texture

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Sweatshirt, FleeceBlanket, BeachTowel, Cushion, Duvet, NotebookA5, PhoneCaseIPhone12, Tshirt, Hoodie, Sweater, BathTowel, DuvetCover, ShowerCurtain, Towel, TshirtMan, TshirtWoman, TshirtWoman2, DuvetCoverOlamide, Cushion2, Cushion1
type Type int32

const (
	Type_Sweatshirt        Type = 0
	Type_FleeceBlanket     Type = 1
	Type_BeachTowel        Type = 2
	Type_Cushion           Type = 3
	Type_Duvet             Type = 4
	Type_NotebookA5        Type = 5
	Type_PhoneCaseIPhone12 Type = 6
	Type_Tshirt            Type = 7
	Type_Hoodie            Type = 8
	Type_Sweater           Type = 9
	Type_BathTowel         Type = 10
	Type_DuvetCover        Type = 11
	Type_ShowerCurtain     Type = 12
	Type_Towel             Type = 13
	Type_TshirtMan         Type = 14
	Type_TshirtWoman       Type = 15
	Type_TshirtWoman2      Type = 16
	Type_DuvetCoverOlamide Type = 17
	Type_Cushion2          Type = 18
	Type_Cushion1          Type = 19
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "Sweatshirt",
		1:  "FleeceBlanket",
		2:  "BeachTowel",
		3:  "Cushion",
		4:  "Duvet",
		5:  "NotebookA5",
		6:  "PhoneCaseIPhone12",
		7:  "Tshirt",
		8:  "Hoodie",
		9:  "Sweater",
		10: "BathTowel",
		11: "DuvetCover",
		12: "ShowerCurtain",
		13: "Towel",
		14: "TshirtMan",
		15: "TshirtWoman",
		16: "TshirtWoman2",
		17: "DuvetCoverOlamide",
		18: "Cushion2",
		19: "Cushion1",
	}
	Type_value = map[string]int32{
		"Sweatshirt":        0,
		"FleeceBlanket":     1,
		"BeachTowel":        2,
		"Cushion":           3,
		"Duvet":             4,
		"NotebookA5":        5,
		"PhoneCaseIPhone12": 6,
		"Tshirt":            7,
		"Hoodie":            8,
		"Sweater":           9,
		"BathTowel":         10,
		"DuvetCover":        11,
		"ShowerCurtain":     12,
		"Towel":             13,
		"TshirtMan":         14,
		"TshirtWoman":       15,
		"TshirtWoman2":      16,
		"DuvetCoverOlamide": 17,
		"Cushion2":          18,
		"Cushion1":          19,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_texture_texture_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_texture_texture_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_texture_texture_proto_rawDescGZIP(), []int{0}
}

type TextureRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Canvas []byte `protobuf:"bytes,1,opt,name=canvas,proto3" json:"canvas,omitempty"`
	Type   Type   `protobuf:"varint,2,opt,name=type,proto3,enum=texture.Type" json:"type,omitempty"`
}

func (x *TextureRequest) Reset() {
	*x = TextureRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_texture_texture_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextureRequest) ProtoMessage() {}

func (x *TextureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_texture_texture_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextureRequest.ProtoReflect.Descriptor instead.
func (*TextureRequest) Descriptor() ([]byte, []int) {
	return file_texture_texture_proto_rawDescGZIP(), []int{0}
}

func (x *TextureRequest) GetCanvas() []byte {
	if x != nil {
		return x.Canvas
	}
	return nil
}

func (x *TextureRequest) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_Sweatshirt
}

type TextureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Texture []byte `protobuf:"bytes,1,opt,name=texture,proto3" json:"texture,omitempty"`
}

func (x *TextureResponse) Reset() {
	*x = TextureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_texture_texture_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextureResponse) ProtoMessage() {}

func (x *TextureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_texture_texture_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextureResponse.ProtoReflect.Descriptor instead.
func (*TextureResponse) Descriptor() ([]byte, []int) {
	return file_texture_texture_proto_rawDescGZIP(), []int{1}
}

func (x *TextureResponse) GetTexture() []byte {
	if x != nil {
		return x.Texture
	}
	return nil
}

var File_texture_texture_proto protoreflect.FileDescriptor

var file_texture_texture_proto_rawDesc = []byte{
	0x0a, 0x15, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x4b, 0x0a, 0x0e, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x63, 0x61, 0x6e, 0x76, 0x61, 0x73, 0x12, 0x21, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0d, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x2b, 0x0a,
	0x0f, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2a, 0xbf, 0x02, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x77, 0x65, 0x61, 0x74, 0x73, 0x68, 0x69, 0x72,
	0x74, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x46, 0x6c, 0x65, 0x65, 0x63, 0x65, 0x42, 0x6c, 0x61,
	0x6e, 0x6b, 0x65, 0x74, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x65, 0x61, 0x63, 0x68, 0x54,
	0x6f, 0x77, 0x65, 0x6c, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x75, 0x73, 0x68, 0x69, 0x6f,
	0x6e, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x44, 0x75, 0x76, 0x65, 0x74, 0x10, 0x04, 0x12, 0x0e,
	0x0a, 0x0a, 0x4e, 0x6f, 0x74, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x35, 0x10, 0x05, 0x12, 0x15,
	0x0a, 0x11, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x43, 0x61, 0x73, 0x65, 0x49, 0x50, 0x68, 0x6f, 0x6e,
	0x65, 0x31, 0x32, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x54, 0x73, 0x68, 0x69, 0x72, 0x74, 0x10,
	0x07, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x6f, 0x6f, 0x64, 0x69, 0x65, 0x10, 0x08, 0x12, 0x0b, 0x0a,
	0x07, 0x53, 0x77, 0x65, 0x61, 0x74, 0x65, 0x72, 0x10, 0x09, 0x12, 0x0d, 0x0a, 0x09, 0x42, 0x61,
	0x74, 0x68, 0x54, 0x6f, 0x77, 0x65, 0x6c, 0x10, 0x0a, 0x12, 0x0e, 0x0a, 0x0a, 0x44, 0x75, 0x76,
	0x65, 0x74, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x10, 0x0b, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x68, 0x6f,
	0x77, 0x65, 0x72, 0x43, 0x75, 0x72, 0x74, 0x61, 0x69, 0x6e, 0x10, 0x0c, 0x12, 0x09, 0x0a, 0x05,
	0x54, 0x6f, 0x77, 0x65, 0x6c, 0x10, 0x0d, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x73, 0x68, 0x69, 0x72,
	0x74, 0x4d, 0x61, 0x6e, 0x10, 0x0e, 0x12, 0x0f, 0x0a, 0x0b, 0x54, 0x73, 0x68, 0x69, 0x72, 0x74,
	0x57, 0x6f, 0x6d, 0x61, 0x6e, 0x10, 0x0f, 0x12, 0x10, 0x0a, 0x0c, 0x54, 0x73, 0x68, 0x69, 0x72,
	0x74, 0x57, 0x6f, 0x6d, 0x61, 0x6e, 0x32, 0x10, 0x10, 0x12, 0x15, 0x0a, 0x11, 0x44, 0x75, 0x76,
	0x65, 0x74, 0x43, 0x6f, 0x76, 0x65, 0x72, 0x4f, 0x6c, 0x61, 0x6d, 0x69, 0x64, 0x65, 0x10, 0x11,
	0x12, 0x0c, 0x0a, 0x08, 0x43, 0x75, 0x73, 0x68, 0x69, 0x6f, 0x6e, 0x32, 0x10, 0x12, 0x12, 0x0c,
	0x0a, 0x08, 0x43, 0x75, 0x73, 0x68, 0x69, 0x6f, 0x6e, 0x31, 0x10, 0x13, 0x32, 0x51, 0x0a, 0x0e,
	0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x12, 0x17, 0x2e, 0x74,
	0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x0b, 0x5a, 0x09, 0x2e, 0x2f, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_texture_texture_proto_rawDescOnce sync.Once
	file_texture_texture_proto_rawDescData = file_texture_texture_proto_rawDesc
)

func file_texture_texture_proto_rawDescGZIP() []byte {
	file_texture_texture_proto_rawDescOnce.Do(func() {
		file_texture_texture_proto_rawDescData = protoimpl.X.CompressGZIP(file_texture_texture_proto_rawDescData)
	})
	return file_texture_texture_proto_rawDescData
}

var file_texture_texture_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_texture_texture_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_texture_texture_proto_goTypes = []interface{}{
	(Type)(0),               // 0: texture.Type
	(*TextureRequest)(nil),  // 1: texture.TextureRequest
	(*TextureResponse)(nil), // 2: texture.TextureResponse
}
var file_texture_texture_proto_depIdxs = []int32{
	0, // 0: texture.TextureRequest.type:type_name -> texture.Type
	1, // 1: texture.TextureService.GetTexture:input_type -> texture.TextureRequest
	2, // 2: texture.TextureService.GetTexture:output_type -> texture.TextureResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_texture_texture_proto_init() }
func file_texture_texture_proto_init() {
	if File_texture_texture_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_texture_texture_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextureRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_texture_texture_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_texture_texture_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_texture_texture_proto_goTypes,
		DependencyIndexes: file_texture_texture_proto_depIdxs,
		EnumInfos:         file_texture_texture_proto_enumTypes,
		MessageInfos:      file_texture_texture_proto_msgTypes,
	}.Build()
	File_texture_texture_proto = out.File
	file_texture_texture_proto_rawDesc = nil
	file_texture_texture_proto_goTypes = nil
	file_texture_texture_proto_depIdxs = nil
}
